server:
  port: 8099

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: mpw:W9Hwy2nTejWg8HhGCHN4ZQHjRBz+RUo7PXjyqXbM/+Al26jZ2HTxtFlkaTUfhdyl/oPrLgQHk7PdlhU6PkQowb08S4QDpbSQGWZT3K+xrh+SuhAofdmv7xj/T0Cht8IXMAx487z+jbgjyXA8chDP0w==
    username: mpw:AoF5H1zNRSQdlEoMXt+cfg==
    password: mpw:AoF5H1zNRSQdlEoMXt+cfg==

mybatis‐plus:
  global‐config:
    db‐config:
      id-type: auto # 全局主键默认自增长
      logic‐delete‐field: active # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic‐not‐delete‐value: 1 # 逻辑未删除值(默认为 1)
      logic‐delete‐value: 0 # 逻辑已删除值(默认为 0)

logging:
  level:
    root: info
    com.mi: debug