server:
  port: 8099

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.p6spy.engine.spy.P6SpyDriver #com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://192.168.68.152:3306/springboot-cli?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.68.152
    port: 6379
    database: 0
    timeout: 1000s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
    cache:
      redis:
        time-to-live: -1 #毫秒
  main:
    allow-bean-definition-overriding: true
mybatis‐plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
  global‐config:
    db‐config:
      id-type: auto # 全局主键默认自增长
      logic‐delete‐field: enabled # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic‐not‐delete‐value: 1 # 逻辑未删除值(默认为 1)
      logic‐delete‐value: 0 # 逻辑已删除值(默认为 0)

logging:
  level:
    root: info
    com.mi: debug